repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy

  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]

# Добавляем pre-push hook, который будет запускать тесты и проверки
  - repo: local
    hooks:
      - id: run-ci-before-push
        name: Run CI checks before push
        entry: uv run mypy src/ && uv run ruff check src/ && uv run pytest -v --maxfail=1
        language: system
        stages: [push]
# repos:
#   - repo: https://github.com/psf/black
#     rev: 24.1.0
#     hooks:
#       - id: black

#   - repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.4.7
#     hooks:
#       - id: ruff
#         args: [--fix]

#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.19.0
#     hooks:
#       - id: mypy
#         args: [--ignore-missing-imports]
