global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["web:8000"]

  - job_name: "rabbitmq"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["rabbitmq:15672"]
